name: First Bash

on:
  push:
    branches:
      - "*"

jobs:
  job1:
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo $MY_SECRET
          touch step1.txt
          echo "hi from step 1" > step1.txt
      - name: step 2
        run: |
          cat step1.txt
  job2:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: step 3
        run: |
          cat step1.txt
